spring:
  application:
    name: user-service
  profile:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/food_ordering_system?currentSchema=user_mgmt&binaryTransfer=true&reWriteBatchedInserts=true
    username: admin
    password: admin

  jpa:
    show-sql: true
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: user_mgmt
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cloud:
    discovery:
      enabled: false

  flyway:
    enabled: true

server:
  port: 8081
  servlet:
    context-path: /user-service


management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"

ecommerce:
  app:
    jwtCookieName: ecommerce
    jwtSecret: "c8d08ea6866c964ff9123c22270502beb2ef2f8194cfaafd6e90601777196b83"
    jwtExpirationMs: 900000 #15 mins
